### ISSUE TITLE
[BUG] "Reverse playfield" option freezes program

### ISSUE THREAD

**Issue by tlsctf2** [tillvit/smeditor#101]
**Version/OS**
both browser and downloadable versions. computer is Windows 10, browser is Firefox. both on latest version

**Describe the bug**
upon clicking the "reverse playfield" option, which I assume switches the editor to downscroll, the entire program freezes and will no longer accept any input. this happens whether selecting the option during editing, or before opening a file; as soon as a chart is loaded with the option enabled, the program freezes and you have to close it completely to do anything else. if it matters, the file I tried to open was a .sm file every time

**To Reproduce**
A:
-open a chart
-go to Preferences > Options
-enable "Reverse playfield" in Chart section

B:
-go to "Preferences > Options"
-enable "Reverse playfield" in Chart section
-open a chart

**Screenshots/Media**
looked for the log file and didn't find one in the provided path (/%LOCALAPPDATA%/smeditor/chrome_debug.log) so I have to assume a log file was not created

**Additional context**
editor functionality can be restored by disabling the option before loading a chart, but the editor will still crash if the option is left enabled and a chart is loaded

**Comment by tillvit** [comment]
There was a bug making the game freeze if the beat was before 0 (and could have been related to downscroll) that was fixed a few days ago, and I can't seem to reproduce it on my end. Have you tried reloading twice to force the browser to use the new version?

**Comment by tlsctf2** [comment]
looks like that did the trick, guess that's on me for not trying that before lol
apologies for the bad report then o7
