### ISSUE TITLE
[FEATURE] Documentation/Tutorial

### ISSUE THREAD

**Issue by synchronisator** [tillvit/smeditor#103]
Sorry for asking here, but i dont know how/where to ask as alternative.

Is there some documentation on how to use the editor?
A overview of functions and a hint how to use them or a  tutorial/small video showing these functions?

- Methods to add/remove/move arrows (record/mouse)
- Copy/paste sequences
- change a holding note to a tap or vice versa
- set an audio offset
- set bpm changes or fermata
- etc.

I found out some of these on my own but i think a reference would be very helpful!

Thanks!

**Comment by tillvit** [comment]
Will look into in the near future

**Comment by tillvit** [comment]
Basic guide written, still working on other pages
https://tillvit.github.io/smeditor/guide/

**Comment by synchronisator** [comment]
Thank you very much for this guide!
It helps a lot!
