### ISSUE TITLE
[FEATURE] remember previous window size

### ISSUE THREAD

**Issue by rehtlaw** [tillvit/smeditor#113]
I would like to see the editor remember it's previous window size, or alternatively give an option to set a manual window resolution somewhere.
I want to use SMEditor on my steam deck, but always being forced into an 800x600-ish window with no option to change the window size (gamescope can't just resize windows, it will always scale them up instead) isn't ideal.

**Comment by tillvit** [comment]
Added in recent update.

**Comment by rehtlaw** [comment]
Thanks for the change, but I don't think setting fullscreen as the default is necessarily a good idea for desktop users.
