### ISSUE TITLE
[FEATURE] NotITG formatted "Type" selection for Export Notedata

### ISSUE THREAD

**Issue by KyDash** [tillvit/smeditor#119]
NotITG's note type format follows a different structure from how SMEditor exports notedata, using the in simfile representation for notetypes. Being able to toggle between between the two would be useful when dealing with NotITG notedata and SMEditor exported notedata in game without the need of manual editing.

On note:
"Tap" becomes 1
"Hold" becomes 2
"Roll" becomes 4
"Mine" becomes "M"

**Comment by tillvit** [comment]
How should lifts be exported since they don't exist in NotITG?

**Comment by KyDash** [comment]
best method would be to keep it consistent with how they show up in an ssc file: they could be written as "L", and "F" for fakes

**Comment by tillvit** [comment]
Added in next update.
