### ISSUE TITLE
[BUG]Loading a new Audio Track breaks the song

### ISSUE THREAD

**Issue by reithegoat** [tillvit/smeditor#128]
**Version/OS**
1.0.0 - Windows 11

**Describe the bug**
When selecting a new Audio Track in the Song Properties window, the Audio Track value changes formatting from "song.ogg" to "C:\directories\song.ogg". The formatting seems to cause SMEditor not to play the audio track. When making an entirely new chart, any selected file is formatted as "song.ogg" and allows the SMEditor to play the song.

**To Reproduce**
1. Open, not make, a song.
2. Open Song Properties under Chart.
3. Select the current Audio Track value to open the file explorer.
4. Select a new audio file.
5. Try to play the song.

**Screenshots/Media**
The Bug: https://github.com/user-attachments/assets/e698d939-7bd2-4cc8-9db4-712256f92b26
Working when making a new song: https://github.com/user-attachments/assets/d6128093-f77c-451b-90f4-c7733c7c1718

[chrome_debug.log](https://github.com/user-attachments/files/16841207/chrome_debug.log)

**Comment by tillvit** [comment]
Fixed in next update.
