### ISSUE TITLE
[BUG] on editing for Pump Double. Button 0 for right pad downleft does not work

### ISSUE THREAD

**Issue by Shen-Black** [tillvit/smeditor#132]
**Version/OS**
1.0

As the title says, and maybe im mistaken since im just playing with this editor now, but im editing some sm for pump and in double, the last arrow, wich on arrowvoltex its 0 to place it on the editor, it seems to refuse to work, putting it with mouse its fine.

**Comment by tillvit** [comment]
Fixed in next update
