### ISSUE TITLE
[FEATURE] Add ability to provide hotkeys to toggle Edit Steps, Edit Timing, and Add Timing Events

### ISSUE THREAD

**Issue by TCHalogen** [tillvit/smeditor#142]
First off, before posting anything -- I'd just like to say, your work on this editor has been absolutely amazing. I've been following it for quite a while and even made a fork to attempt to do stuff with it since JavaScript/TypeScript is my day to day, but time hasn't particularly been on my side to really get a feel for how it works.

In any case, just wanted to get that out there. Keep up the amazing work!

****

**Describe the feature you'd like**
Currently, the editor does not provide the capability to add any sort of shortcut for changing between Edit Steps/Edit Timing, nor does it have the ability to toggle in and out between adding a new Timing Event. Providing hotkeys for these particular actions will dramatically expedite the speed of which people make XMod-intensive charts.

**Comment by tillvit** [comment]
Added in next update.
