### ISSUE TITLE
[BUG] Improper label for conversion of tap notes to mines

### ISSUE THREAD

**Issue by TCHalogen** [tillvit/smeditor#143]
**Version/OS**
Windows 11 23H2 (22631.4317)

**Describe the bug**
The label for converting a tap note to a mine is incorrect (simple typo, easy clean up).

**To Reproduce**
Go to options, choose Selection and observe the incorrect label.

**Screenshots/Media**
![image](https://github.com/user-attachments/assets/f4634bb0-f0ff-4472-b8c0-e9b5fe1e40d8)

**Comment by tillvit** [comment]
Fixed in next update.
