### ISSUE TITLE
[BUG] NPS graph from previous chart state persists when current chart has zero steps

### ISSUE THREAD

**Issue by TCHalogen** [tillvit/smeditor#144]
**Version/OS**
Windows 11 23H2 (22631.4317)

**Describe the bug**
When creating a new chart, or removing all steps from a chart and switching to a previous chart, the previous chart's NPS graph will persist.

**To Reproduce**
- Navigate to a chart that contains at least one step
- Either create a new chart or remove all steps from any existing chart
- If removing steps from a previous chart, navigate back to the first chart with steps, then navigate to the empty chart
- Observe the NPS graph retaining the previous chart's values

**Screenshots/Media**
#### Switching from existing Expert, to empty Medium chart:
![image](https://github.com/user-attachments/assets/847c9dd3-5fbf-4abf-8c06-ec795b3f6ace)
![image](https://github.com/user-attachments/assets/0ddd9382-2183-4082-9441-a60ecf278dcd)

#### Switching from existing Hard, to empty Medium chart:
![image](https://github.com/user-attachments/assets/e824d677-f8f2-4c34-939c-2494072006ad)
![image](https://github.com/user-attachments/assets/6f36ec67-ffb9-482a-96e9-f37be63adc8a)

#### Adding a step to Medium difficulty, then emptying Medium chart:
![image](https://github.com/user-attachments/assets/5d36304e-72ef-47af-8460-9a9407c68f75)
![image](https://github.com/user-attachments/assets/0931115b-c3d6-48b1-93a7-e7a91d8183a3)

**Comment by tillvit** [comment]
Fixed in next update.
