### ISSUE TITLE
[BUG] Split timing functionality currently non-functional

### ISSUE THREAD

**Issue by TCHalogen** [tillvit/smeditor#145]
Please let me know if I'm posting things at too high of a frequency, as an aside. I genuinely love using this editor and am very much wanting to use this over ArrowVortex already.

As an aside, this ticket can _potentially_ be broken down into two discrete issues. I can separate them if you'd like.

## Version/OS
Windows 11 23H2 (22631.4317)

## Bug Description
1.) Chart-specific timing events are not constrained to the chart they're being applied to if they have not been designated as a split-timing chart.
2.) Chart-specific timing events _are_ constrained to the appropriate difficulty if a loaded chart is designated as a split-timing chart, but saving causes unpredictable behavior that not only discards the intended timings, but seems to apply them to other charts as well.

### Issue 1
- Load a simfile that is not designated as a split-timing chart
- Attempt to apply a timing event either via a.) **Edit Timing > Add Timing Event** or b.) **Edit Timing Event At Row**
- For A, add a timing event on the playfield that would cause the chart to be designated as split-timing; observe that the timing event gets added to all charts
- For B, add a timing event intended to be for the current chart only that would cause the chart to be designated as split-timing; observe that the timing event gets added to all charts

### Issue 2
- Load a simfile that is designated as a split-timing chart
- Attempt to apply a timing event either via a.) **Edit Timing > Add Timing Event** or b.) **Edit Timing Event At Row**
- For A, observe the following behavior when attempting to apply to the current chart: addition of fakes, delays, warps, stops and attacks apply to all charts -- additionally, removal of fakes, delays, warps, stops and attacks remove from all charts
- For B, observe the following behavior when attempting to apply to the current chart: addition of fakes, delays, warps and stops are the only things possible; all other properties appear to be immutable within this menu

## Screenshots

**Expert Difficulty** - all timing events intended only for this difficulty; all other difficulties prior to the application of this are empty
![image](https://github.com/user-attachments/assets/c5117703-58b4-4fa2-a1f1-1f1f9609cd6f)

**After adding timing events to Expert** -- present in all other charts
![image](https://github.com/user-attachments/assets/298acf20-750c-445d-9914-b3ced40d27d4)

**After removing timing events from any difficulty**
![image](https://github.com/user-attachments/assets/cd8e3f29-8626-417c-bd5f-c71968696041)

### Additional Context
- After saving, only fakes, delays, warps, stops and attacks remain from the intended timing change, on all difficulties.
- **Saving after removal of these added timings on any difficulty will unpredictably cause charts to disappear.** After adding the timings to a 5-difficulty set (B/E/M/H/X), X disappeared from the game but still existed in the .ssc file. 
- After removing the X difficulty to make the set a 4-difficulty set and running through the process of adding/removing the timings again, I was left with only B/E being accessible in SMEditor, and B/E/M within the .ssc file -- that is to say, the H appeared to be deleted from the .ssc.

### Logs
[chrome_debug.log](https://github.com/user-attachments/files/17356047/chrome_debug.log)

**Comment by tillvit** [comment]
Yeah I think adding them is nonfunctional but loading them isn't. There's groundwork for supporting editing them but I haven't really figured out a nice workflow for it (also UI considerations).
I need to somehow make it clear if a column is in chart timing/song timing somehow at a glance and tell the user that things will be deleted if they decide to swap back to song timing. 
It's a hard design problem that I've postponed for 1+ years but it might be time to start thinking about it haha

**Comment by TCHalogen** [comment]
Yeah, I was playing around with the code myself and couldn't find a way to make the timing event popup box to look particularly good. Adding a checkbox with the **isChartTiming** property as a key seemed to appropriately cause the file to save as split timing, but it didn't look particularly good after a quick playaround with it.

Loading them is definitely fine; I had to just basically go back and forth between your editors to make things work now that I've gotten used to the workflow of your editor, hahaha

**Comment by tillvit** [comment]
Proposed solution for now (will add a button to toggle all tracks to be chart/song timing
https://github.com/user-attachments/assets/05e810ee-ec79-47ff-b62a-7dfcb77642c1

**Comment by tillvit** [comment]
Fixed in next update.
