### ISSUE TITLE
[BUG] Adding tags that already exists

### ISSUE THREAD

**Issue by renansimoes** [tillvit/smeditor#146]
***Before posting, please check for other ideas that may be similar to yours!***

**Version/OS**
Windows 11

**Describe the bug**
After using for sometime, stepp1 wasn't recognizing the steps (it was totally blank in game). I openned the SSC and the editor inserted those tags in each chart:

#CREDIT:;
#METERF:;

Credit already existed in each chart and editor added another one, and I don't know why it added MeterF instead of changing the already existant Meter.

Deleting those tags made StepP1 recognize steps again.

**To Reproduce**
Open a .ssc with charts, change chart meter and credit (artist in sme). Save it.

**Screenshots/Media**
If applicable, add screenshots to help explain your problem. Logs of the developer console are great, but videos demonstrating the bug are even better!
If you are using the app, logs are located at 
- Windows: ``%LOCALAPPDATA%/smeditor/chrome_debug.log``
- Linux: ``~/.config/smeditor/chrome_debug.log``
- OS X: ``~/Library/Application Support/smeditor/chrome_debug.log``

**Additional context**

**Comment by tillvit** [comment]
Do you have an example sec that I can you to reproduce the bug?

**Comment by renansimoes** [comment]
I tested again and #CREDIT:; is changing fine (maybe I've done something wrong in notepad++). But it still adds #METERF:;

- Copy a .ssc
- Open SME and open this copied .ssc
- Select "Chart" > Chart List
- Select the chart, change meter level, save it.

**Comment by tillvit** [comment]
METERF and METER are different tags, I think Outfox adds METERF. Does this break StepP1?

**Comment by renansimoes** [comment]
Just tested here, it doesn't break.

I don't know WTH broke it, but it's fixed now. Sorry for the incovenience. You can close this issue.
