### ISSUE TITLE
[BUG] Inverted scroll direction when in reverse not working

### ISSUE THREAD

**Issue by northerncarrots** [tillvit/smeditor#155]
**Version/OS**
Windows 10 Pro 22H2

**Describe the bug**
Scrolling down moves the sheet up and scrolling up moves the sheet down.
Enabling the `Inverted scroll direction when in reverse` option has no effect.

**To Reproduce**
1. Enable the `Reverse playfield` option.
2. Scroll to move the playfield.

**Screenshots/Media**
https://github.com/user-attachments/assets/0db48155-9924-41c2-9e0d-d524b3a5be6e

**Additional context**
When the playfield is reversed in the video, scrolling moves the playfield in the opposite direction.

**Comment by northerncarrots** [comment]
You can work around this by setting the note snap to the 0th note.

**Comment by tillvit** [comment]
Fixed in next update.
