### ISSUE TITLE
[BUG] Saving a file with SMEditor messes up the file

### ISSUE THREAD

**Issue by StarUndrscre** [tillvit/smeditor#157]
**Version/OS**
v1.0 Standalone/Windows 11 22H2 (22621.1610)

**Describe the bug**
Saving a file with the standalone version of SMEditor does really weird things to the end of the file; sometimes it messes up quants and it doesn't add the semicolon to the very end of the `#NOTES` field + some of the chart data is missing.

**To Reproduce**
Make a new song, place down some notes, save, and check the SM/SSC file

**Screenshots/Media**
[chrome_debug.log](https://github.com/user-attachments/files/17942577/chrome_debug.log)

_(Left is the file saved by ArrowVortex, right is the file saved by SMEditor)_
![](http://us-east-1.tixte.net/uploads/star.needs.rest/VSCodium_Y6Dmh96EdE.png)

![](https://star.needs.rest/r/VSCodium_wU3Nvlg1rP.png)

![](https://star.needs.rest/r/sublime_text_c4J6IpBNwS.png)

**Additional Context**
This only happens for the specific file I'm trying to make; it doesn't happen on any other file that I've tested

**Comment by tillvit** [comment]
Made a fix in the next update, hopefully that was it
Was truncating the end of the file after writing to it, but the length calculation to determine where to truncate doesn't like special characters

Unicode Strikes Again 
