### ISSUE TITLE
[BUG] Cant set gameplay bindings to 12345 ( making record mode less useful )

### ISSUE THREAD

**Issue by 2minwia** [tillvit/smeditor#158]
***Before posting, please check for other ideas that may be similar to yours!***

**Version/OS**
Windows, 1.0.0
**Describe the bug**
It's not possible to set the gameplay bindings to any numbers, which makes record-mode very confusing for people coming from arrowvortex.
**To Reproduce**
Attempt to set a gameplay binding to a number.

**Screenshots/Media**
N/A

**Additional context**
Also, placing notes while playing the song ( not in record mode ) works, but they're unsnapped. This is a bit unintuitive? I'd rather just have them snap, but adding salt to the wound, I can actually use 12345 while in song-playing mode.

**Comment by tillvit** [comment]
Fixed in next update
