### ISSUE TITLE
[BUG] Unable to place down notes + mousewheel scroll is reversed

### ISSUE THREAD

**Issue by KyDash** [tillvit/smeditor#162]
As title mentions, in the 1.1.0 version of SMEditor, it is not possible to place down notes using the number row.
In addition the, default scrolling direction using the mouse wheel is inverted in comparison to previous versions, though toggling on the `Invert scroll direction when in reverse` returns the direction to default, despite reverse not being enabled.

This currently occurs on both the native executable and browser version (tested using Waterfox 6.5.2)

Open a chart in editor, attempt to place down any notes or scroll.

**Comment by tillvit** [comment]
fibxed in next gupdate ຦
