### ISSUE TITLE
[BUG]Charts won't save, chart creation doesn't work properly

### ISSUE THREAD

**Issue by BagelGD** [tillvit/smeditor#165]
MacOS 15.0.1, Safari 18.0.1

When opening an existing .sm or .ssc file, it won't save [Failed to save file: the object could not be cloned]
When trying to create a new song, the audio will not upload
When I create a new song, I get put back at the Open a Song window
Even if there is an audio file, the chart does not recognize it
Exporting a song results in a Zero KB .sm file

![Screenshot 2024-12-14 at 12 18 42 PM](https://github.com/user-attachments/assets/f1eab0b6-8462-4156-b33a-a2c5a165737f)
![Screenshot 2024-12-14 at 12 18 17 PM](https://github.com/user-attachments/assets/f466e8ed-5bba-4b0e-8cc7-66d97e6b80de)
![Screenshot 2024-12-14 at 12 18 04 PM](https://github.com/user-attachments/assets/4b518b2b-630c-4685-8401-9ef055a0a803)

**Comment by tillvit** [comment]
Fixed in next update
