### ISSUE TITLE
[BUG] Creating a new song in SMEditor obliterates the audio file

### ISSUE THREAD

**Issue by LemmaEOF** [tillvit/smeditor#167]
**Version/OS**
Electron app 1.1.1 on MacOS 14.3

**Describe the bug**
Whenever you create a new song in SMEditor, it will kick you back to the splash screen and overwrite the selected audio file with an empty .ogg.

**To Reproduce**
- hit New Song on the start screen
- Select your .ogg song to use
- Hit "Create"
- Save the .sm file in the same folder as the .ogg
- You will now be on the start screen and your .ogg has now been destroyed

**Screenshots/Media**
![Capto_Capture 2024-12-17_05-36-05_PM](https://github.com/user-attachments/assets/cbeb6367-f209-43c7-a2d2-088091aac5b9)
![Capto_Capture 2024-12-17_05-37-26_PM](https://github.com/user-attachments/assets/0034dc8e-12cf-4fbc-aa91-be1f896585bc)
![Capto_Capture 2024-12-17_05-37-52_PM](https://github.com/user-attachments/assets/66a8d907-5810-49f7-88ca-779243d1fe64)
![Capto_Capture 2024-12-17_05-38-22_PM](https://github.com/user-attachments/assets/2f8f573b-4213-4a5b-b21c-b6d2db8bbc9b)
https://paste.gg/p/anonymous/537693e46641434e958d871828ce06c7

**Comment by tillvit** [comment]
should be hopefully fixed now
