### ISSUE TITLE
Creating Holds hardbound to up/down

### ISSUE THREAD

**Issue by Piols** [tillvit/smeditor#69]
I downloaded the windows v0.1.0-beta release. I switched moving cursor up/down to Numpad5 and Numpad2. I cannot create holds by holding 1-4 and going up/down with Numpad5/Numpad2, I must still use up/down, even though I can't use them to normally move my cursor. This is unintuitive, and I believe that it was simply an oversight.

**Comment by tillvit** [comment]
Fixed in next update.
