### ISSUE TITLE
QoL request: Better control of receptor position

### ISSUE THREAD

**Issue by Piols** [tillvit/smeditor#70]
I downloaded the windows v0.1.0-beta release. If I understand correctly, the only way to control the receptor position on the screen is to choose a Y offset from the center in pixels. I find it much more useful for the receptors to be positioned as a fixed ratio of the height of the window. Because now if I change the width of the window, or simply maximize it, the receptors height changes and they can even go off screen.

Also the horizontal position of the receptors cannot be set from what I tried, which is mildly infuriating given they skew to the left and are offcenter, especially at higher widths.

**Comment by tillvit** [comment]
Added receptor dragging but x&y position are still pixel-based. Might look into making them position based (have to write some options migration system) later.
