### ISSUE TITLE
inverted scroll in reverse

### ISSUE THREAD

**Issue by mikatheidiot** [tillvit/smeditor#77]
the option to invert the mousewheel scrolling when the playfield is reversed has no effect

**Comment by tillvit** [comment]
Fixed in next update.

**Comment by tillvit** [comment]
> I'm experiencing this issue in both the desktop and web app. Scrolling down moves the sheet up and scrolling up moves the sheet down with the option having no effect.

if you still have this problem, can you record a video reproducing the bug and open a new issue?
