### ISSUE TITLE
alternate noteskin support

### ISSUE THREAD

**Issue by mikatheidiot** [tillvit/smeditor#78]
it would be nice to have support for adding custom noteskins. the dream would be if it was possible to load noteskins exactly as used for sm, but being able to just swap out note graphics without having to rebuild would be good as well

**Comment by tillvit** [comment]
Would require a large rewrite of the noteskin system. Loading noteskins directly from a folder would require running Lua in the browser, which is a bit too overkill for one small feature.

**Comment by tillvit** [comment]
Small update: I've rewrote how notes are drawn on the screen, meaning noteskin support is somewhat possible. Noteskins will not be written in Lua though.

**Comment by tillvit** [comment]
Noteskin support has been added in dev branch, but user note skins cannot be loaded; there will just be a set of note skins to select from
