### ISSUE TITLE
Add descriptions to the buttons in the edit menu

### ISSUE THREAD

**Issue by GamerOn117** [tillvit/smeditor#79]
***Before posting, please check for other ideas that may be similar to yours!***

**Describe the feature you'd like**
I would like the buttons in the edit menu to have descriptions. They don't have to be intrusive, you can just make them appear after hovering over them for a second

The only reason I want these is so that these two arrow types are more clear on what they are (because I have no idea)
![Screenshot 2023-12-02 174525](https://github.com/tillvit/smeditor/assets/69049300/5edcbc82-06cd-4cca-bd45-bd32b4aa2a54)

**Comment by tillvit** [comment]
Added in next update
