### ISSUE TITLE
Rolls/holds that start and end within the range of another do not have their tails saved

### ISSUE THREAD

**Issue by KyDash** [tillvit/smeditor#81]
If a roll or hold is contained within the length of another (ex: Hold on column 4 spans beat 4 to 6, and a second hold on column 2 spans beat 4.5 to 5), the tail of the shorter hold does not get saved.
The columns containing the holds/rolls are not relevant, and only happens to those that fall entirely within the range of another, any other setup saves correctly
https://github.com/tillvit/smeditor/assets/13700883/2a4f51a7-2fcd-4fae-aac7-98f820cc06eb

**Comment by tillvit** [comment]
Fixed in next update
