### ISSUE TITLE
QoL: Copy-Paste overwrite existing arrows

### ISSUE THREAD

**Issue by mangoafterdawn** [tillvit/smeditor#95]
Currently, pasting a selection of notes over an area containing notes will mix both selections' notes together, instead of replacing
A chart containing:
L---
-D--
--U-
---R

In clipboard:
L---
--U-
-D--
---R

After a paste:
L---
-DU-
-DU-
---R

Unsure if this behavior is intended, but having a way to overwrite instead would be nice to save time deleting regions of notes manually.

**Comment by tillvit** [comment]
Added in next update: use Shift+Paste
