### ISSUE TITLE
It's possible to create zero length holds/rolls when replacing an arrow and scrolling up

### ISSUE THREAD

**Issue by KyDash** [tillvit/smeditor#96]
When placing down an arrow where an arrow already exists, scrolling up while keeping the respective "place arrow" key down will generate a zero length hold/roll.

https://github.com/tillvit/smeditor/assets/13700883/0f84ca47-5d4d-4cfe-ade1-a953b7bdd647

**Comment by tillvit** [comment]
Fixed in next update
